@echo off
rem Keep every heavy ACE-Step download, cache and temporary file inside E:\Portfolio.
rem This file is called by both installation and runtime launchers.

set "ACESTEP_ROOT=%~dp0server\vendors\ACE-Step-1.5"
set "ACESTEP_CHECKPOINTS_DIR=%~dp0server\models\ACE-Step-1.5"
set "ACESTEP_LOCAL_STORAGE=%~dp0server\.local_storage\acestep"
set "ACESTEP_BOOTSTRAP_VENV=%~dp0server\.music_bootstrap_venv"

set "TEMP=%ACESTEP_LOCAL_STORAGE%\tmp"
set "TMP=%TEMP%"
set "TMPDIR=%TEMP%"
set "UV_CACHE_DIR=%ACESTEP_LOCAL_STORAGE%\uv-cache"
set "UV_PYTHON_INSTALL_DIR=%ACESTEP_LOCAL_STORAGE%\uv-python"
set "UV_TOOL_DIR=%ACESTEP_LOCAL_STORAGE%\uv-tools"
set "UV_TOOL_BIN_DIR=%ACESTEP_LOCAL_STORAGE%\uv-tools-bin"
set "PIP_CACHE_DIR=%ACESTEP_LOCAL_STORAGE%\pip-cache"
set "HF_HOME=%ACESTEP_LOCAL_STORAGE%\huggingface"
set "HF_HUB_CACHE=%HF_HOME%\hub"
set "HUGGINGFACE_HUB_CACHE=%HF_HUB_CACHE%"
set "HF_XET_CACHE=%HF_HOME%\xet"
set "TRANSFORMERS_CACHE=%HF_HOME%\transformers"
set "TORCH_HOME=%ACESTEP_LOCAL_STORAGE%\torch"
set "TORCHINDUCTOR_CACHE_DIR=%ACESTEP_LOCAL_STORAGE%\torchinductor"
set "TRITON_CACHE_DIR=%ACESTEP_LOCAL_STORAGE%\triton"
set "NUMBA_CACHE_DIR=%ACESTEP_LOCAL_STORAGE%\numba"
set "CUDA_CACHE_PATH=%ACESTEP_LOCAL_STORAGE%\cuda-cache"
set "XDG_CACHE_HOME=%ACESTEP_LOCAL_STORAGE%\xdg-cache"
set "XDG_CONFIG_HOME=%ACESTEP_LOCAL_STORAGE%\xdg-config"
set "XDG_DATA_HOME=%ACESTEP_LOCAL_STORAGE%\xdg-data"
set "MODELSCOPE_CACHE=%ACESTEP_LOCAL_STORAGE%\modelscope"

if not exist "%ACESTEP_LOCAL_STORAGE%" mkdir "%ACESTEP_LOCAL_STORAGE%"
if not exist "%TEMP%" mkdir "%TEMP%"
if not exist "%UV_CACHE_DIR%" mkdir "%UV_CACHE_DIR%"
if not exist "%PIP_CACHE_DIR%" mkdir "%PIP_CACHE_DIR%"
if not exist "%HF_HOME%" mkdir "%HF_HOME%"
if not exist "%TORCH_HOME%" mkdir "%TORCH_HOME%"
if not exist "%TORCHINDUCTOR_CACHE_DIR%" mkdir "%TORCHINDUCTOR_CACHE_DIR%"
if not exist "%TRITON_CACHE_DIR%" mkdir "%TRITON_CACHE_DIR%"
if not exist "%NUMBA_CACHE_DIR%" mkdir "%NUMBA_CACHE_DIR%"
if not exist "%CUDA_CACHE_PATH%" mkdir "%CUDA_CACHE_PATH%"
